In [14]:
import pandas as pd

# Microatividade 1
dados = pd.read_csv(
    "dados.csv",
    sep=";",
    engine="python",
    encoding="utf-8"
)

display("CONJUNTO ORIGINAL:")
display(dados)

# Microatividade 2
subconjunto = dados[["Duration", "Pulse", "Calories"]]

display("\nSUBCONJUNTO:")
display(subconjunto)

# Microatividade 3
pd.set_option("display.max_rows", 9999)

display("\nCONJUNTO COMPLETO:")
display(dados.to_string())

# Exibe as 10 primeiras linhas
print("PRIMEIRAS 10 LINHAS:")
print(dados.head(10))

# Exibe as 10 últimas linhas
print("\nÚLTIMAS 10 LINHAS:")
print(dados.tail(10))

# Informações gerais do DataFrame
display(dados.info())

'CONJUNTO ORIGINAL:'

    ID  Duration          Date  Pulse  Maxpulse Calories
0    0        60  '2020/12/01'    110       130     4091
1    1        60  '2020/12/02'    117       145     4790
2    2        60  '2020/12/03'    103       135     3400
3    3        45  '2020/12/04'    109       175     2824
4    4        45  '2020/12/05'    117       148     4060
5    5        60  '2020/12/06'    102       127     3000
6    6        60  '2020/12/07'    110       136     3740
7    7       450  '2020/12/08'    104       134     2533
8    8        30  '2020/12/09'    109       133     1951
9    9        60  '2020/12/10'     98       124     2690
10  10        60  '2020/12/11'    103       147     3293
11  11        60  '2020/12/12'    100       120     2507
12  12        60  '2020/12/12'    100       120     2507
13  13        60  '2020/12/13'    106       128     3453
14  14        60  '2020/12/14'    104       132     3793
15  15        60  '2020/12/15'     98       123     2750
16  16        60  '2020/12/16'     98       120     2152
17  17        60  '2020/12/17'    100       120     3000
18  18        45  '2020/12/18'     90       112      NaN
19  19        60  '2020/12/19'    103       123     3230
20  20        45  '2020/12/20'     97       125   2430 2
21   1        60  '2020/12/21'    108       131     3642
22  22        45           NaN    100       119     2820
23  23        60  '2020/12/23'    130       101     3000
24  24        45  '2020/12/24'    105       132     2460
25  25        60  '2020/12/25'    102       126     3345
26  26        60      20201226    100       120     2500
27  27        60  '2020/12/27'     92       118     2410
28  28        60  '2020/12/28'    103       132      NaN
29  29        60  '2020/12/29'    100       132     2800
30  30        60  '2020/12/30'    102       129     3803
31  31        60  '2020/12/31'     92       115     2430

'\nSUBCONJUNTO:'

    Duration  Pulse Calories
0         60    110     4091
1         60    117     4790
2         60    103     3400
3         45    109     2824
4         45    117     4060
5         60    102     3000
6         60    110     3740
7        450    104     2533
8         30    109     1951
9         60     98     2690
10        60    103     3293
11        60    100     2507
12        60    100     2507
13        60    106     3453
14        60    104     3793
15        60     98     2750
16        60     98     2152
17        60    100     3000
18        45     90      NaN
19        60    103     3230
20        45     97   2430 2
21        60    108     3642
22        45    100     2820
23        60    130     3000
24        45    105     2460
25        60    102     3345
26        60    100     2500
27        60     92     2410
28        60    103      NaN
29        60    100     2800
30        60    102     3803
31        60     92     2430

'\nCONJUNTO COMPLETO:'

"    ID  Duration          Date  Pulse  Maxpulse Calories\n0    0        60  '2020/12/01'    110       130     4091\n1    1        60  '2020/12/02'    117       145     4790\n2    2        60  '2020/12/03'    103       135     3400\n3    3        45  '2020/12/04'    109       175     2824\n4    4        45  '2020/12/05'    117       148     4060\n5    5        60  '2020/12/06'    102       127     3000\n6    6        60  '2020/12/07'    110       136     3740\n7    7       450  '2020/12/08'    104       134     2533\n8    8        30  '2020/12/09'    109       133     1951\n9    9        60  '2020/12/10'     98       124     2690\n10  10        60  '2020/12/11'    103       147     3293\n11  11        60  '2020/12/12'    100       120     2507\n12  12        60  '2020/12/12'    100       120     2507\n13  13        60  '2020/12/13'    106       128     3453\n14  14        60  '2020/12/14'    104       132     3793\n15  15        60  '2020/12/15'     98       123     2750\n16  16        60  '2020/12/16'     98       120     2152\n17  17        60  '2020/12/17'    100       120     3000\n18  18        45  '2020/12/18'     90       112      NaN\n19  19        60  '2020/12/19'    103       123     3230\n20  20        45  '2020/12/20'     97       125   2430 2\n21   1        60  '2020/12/21'    108       131     3642\n22  22        45           NaN    100       119     2820\n23  23        60  '2020/12/23'    130       101     3000\n24  24        45  '2020/12/24'    105       132     2460\n25  25        60  '2020/12/25'    102       126     3345\n26  26        60      20201226    100       120     2500\n27  27        60  '2020/12/27'     92       118     2410\n28  28        60  '2020/12/28'    103       132      NaN\n29  29        60  '2020/12/29'    100       132     2800\n30  30        60  '2020/12/30'    102       129     3803\n31  31        60  '2020/12/31'     92       115     2430"

PRIMEIRAS 10 LINHAS:
   ID  Duration          Date  Pulse  Maxpulse Calories
0   0        60  '2020/12/01'    110       130     4091
1   1        60  '2020/12/02'    117       145     4790
2   2        60  '2020/12/03'    103       135     3400
3   3        45  '2020/12/04'    109       175     2824
4   4        45  '2020/12/05'    117       148     4060
5   5        60  '2020/12/06'    102       127     3000
6   6        60  '2020/12/07'    110       136     3740
7   7       450  '2020/12/08'    104       134     2533
8   8        30  '2020/12/09'    109       133     1951
9   9        60  '2020/12/10'     98       124     2690

ÚLTIMAS 10 LINHAS:
    ID  Duration          Date  Pulse  Maxpulse Calories
22  22        45           NaN    100       119     2820
23  23        60  '2020/12/23'    130       101     3000
24  24        45  '2020/12/24'    105       132     2460
25  25        60  '2020/12/25'    102       126     3345
26  26        60      20201226    100       120     2500
27  27        60  '2020/12/27'     92       118     2410
28  28        60  '2020/12/28'    103       132      NaN
29  29        60  '2020/12/29'    100       132     2800
30  30        60  '2020/12/30'    102       129     3803
31  31        60  '2020/12/31'     92       115     2430
<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        32 non-null     int64
 1   Duration  32 non-null     int64
 2   Date      31 non-null     str
 3   Pulse     32 non-null     int64
 4   Maxpulse  32 non-null     int64
 5   Calories  30 non-null     str
dtypes: int64(4), str(2)
memory usage: 1.6 KB

None

    Duration  Pulse Calories
0         60    110     4091
1         60    117     4790
2         60    103     3400
3         45    109     2824
4         45    117     4060
5         60    102     3000
6         60    110     3740
7        450    104     2533
8         30    109     1951
9         60     98     2690
10        60    103     3293
11        60    100     2507
12        60    100     2507
13        60    106     3453
14        60    104     3793
15        60     98     2750
16        60     98     2152
17        60    100     3000
18        45     90      NaN
19        60    103     3230
20        45     97   2430 2
21        60    108     3642
22        45    100     2820
23        60    130     3000
24        45    105     2460
25        60    102     3345
26        60    100     2500
27        60     92     2410
28        60    103      NaN
29        60    100     2800
30        60    102     3803
31        60     92     2430